name: Update Cargo dependency cache
outputs:
  crates-io-index-head:
    value: ${{ steps.crates-io-index-head.outputs.head }}
  cargo-lock-hash:
    value: ${{ steps.cargo-lock-hash.outputs.hash }}
runs:
  using: composite
  steps:
    - id: crates-io-index-head
      name: Get head commit hash of crates.io registry index
      run: |
        commit=$(
          git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
          cut -f 1
        )
        echo "::set-output name=head::$commit"

    - id: cargo-lock-hash
      name: Calculate dependency cache key
      run: |
        hash=$(
          ci/strip-own-version-from-cargo-lock.pl Cargo.lock |
          sha1sum | cut -d ' ' -f 1
        )
        echo "::set-output name=hash::$hash"

    - using: ./.github/actions/cache-init
      with:
        crates-io-index-head: ${{ steps.crates-io-index-head.outputs.head }}
        cargo-lock-hash: ${{ steps.cargo-lock-hash.outputs.hash }}

    - name: Fetch dependencies and update cargo registry
      run: cargo fetch --locked
