bootstrap_from_trusted_peers: true
leadership:
  logs_capacity: 1024
log:
  format: plain
  level: debug
  output: stdout
mempool:
  log_max_entries: 100000
  pool_max_entries: 400000
p2p:
  allow_private_addresses: true
  layers:
    preferred_list:
      peers:
        - address: /ip4/172.20.200.1/tcp/30700
        - address: /ip4/172.20.200.2/tcp/30700
        - address: /ip4/172.20.200.3/tcp/30700
      view_max: 20
    topics_of_interest:
      messages: high
      blocks: high
  listen: "0.0.0.0:30700"
  max_bootstrap_attempts: 3
  max_client_connections: 192
  max_connections: 256
  policy:
    quarantine_duration: 5s
    quarantine_whitelist:
      - /ip4/172.20.200.1/tcp/30700
      - /ip4/172.20.200.2/tcp/30700
      - /ip4/172.20.200.3/tcp/30700
  public_address: /ip4/172.20.200.0/tcp/30700
  trusted_peers:
    - address: /ip4/172.20.200.1/tcp/30700
    - address: /ip4/172.20.200.2/tcp/30700
    - address: /ip4/172.20.200.3/tcp/30700
prometheus:
  enabled: true
rest:
  listen: "0.0.0.0:8080"
skip_bootstrap: true
