openapi: 3.0.2

info:
  title: Generic blockchain node REST API
  description: Jörmungandr Rest API v2
  version: 0.0.1
  contact:
    url: 'https://github.com/input-output-hk/jormungandr/'

servers:
  - url: 'https://localhost'

tags:
  - name: address_mapping

path:
  /api/v2/address_mapping/jormungandr_address/{evm_hex_id}:
    get:
    description: Gets corresponded, mapped jormungadr address for the provided evm address
    operationId: AddressMappingJorId
    tags:
      - address_mapping
    parameters:
      - in: path
        name: evm_hex_id
        required: true
        description: Hex-encoded evm address.
        schema:
          type: string
          pattern: '[0-9a-f]+'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: string
              description: hex encoded jormungandr address

path:
  /api/v2/address_mapping/evm_address/{jor_hex_id}:
    get:
    description: Gets corresponded, mapped evm address for the provided jormungandr address
    operationId: AddressMappingEvmId
    tags:
      - address_mapping
    parameters:
      - in: path
        name: jor_hex_id
        required: true
        description: Hex-encoded jormungandr address.
        schema:
          type: string
          pattern: '[0-9a-f]+'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: string
              description: hex encoded evm address
