name: Setup Nix Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: 'Cachix Auth Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          accept-flake-config = true
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/

    - uses: cachix/cachix-action@v10
      with:
        name: iog
        authToken: '${{ inputs.CACHIX_AUTH_TOKEN }}'
