export const CREATE_CHANNEL_IN_PROGRESS = 'CREATE_CHANNEL_IN_PROGRESS'
export const CHANNEL_CREATED = 'CHANNEL_CREATED'
export const CHANNEL_NOT_CREATED = 'CHANNEL_NOT_CREATED'
export const CHANNEL_RESET = 'CHANNEL_RESET'