[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2021"

[dependencies]
chain-impl-mockchain = { git = "https://github.com/cardano-foundation/chain-libs.git", branch = "phoenix-dynamic-voters" }
chain-time           = { git = "https://github.com/cardano-foundation/chain-libs.git", branch = "phoenix-dynamic-voters"}
thiserror = "1.0.30"
lru       = "0.7"
