#!/bin/sh

### CONFIGURATION

CLI=jcli
NODE=jormungandr

FAUCET_AMOUNT=1000000000
ADDRTYPE="--testing"

### COLORS
GREEN="\033[0;32m"
RED="\033[0;31m"
BLUE="\033[0;33m"
WHITE="\033[0m"

### MAKE EVERYTHING

# faucet
FAUCET_SK=$($CLI key generate --type=Ed25519Extended)
FAUCET_PK=$(echo ${FAUCET_SK} | $CLI key to-public)
FAUCET_ADDR=$($CLI address account ${ADDRTYPE} ${FAUCET_PK})

# leader
LEADER_SK=$($CLI key generate --type=Ed25519)
LEADER_PK=$(echo ${LEADER_SK} | $CLI key to-public)

# stake pool
POOL_VRF_SK=$($CLI key generate --type=Curve25519_2HashDH)
POOL_KES_SK=$($CLI key generate --type=SumEd25519_12)

POOL_VRF_PK=$(echo ${POOL_VRF_SK} | $CLI key to-public)
POOL_KES_PK=$(echo ${POOL_KES_SK} | $CLI key to-public)

# note we use the faucet as the owner to this pool
STAKE_KEY=${FAUCET_SK}
STAKE_KEY_PUB=${FAUCET_PK}

echo ${STAKE_KEY} > stake_key.sk
echo ${POOL_VRF_SK} > stake_pool.vrf.sk
echo ${POOL_KES_SK} > stake_pool.kes.sk

$CLI certificate new stake-pool-registration \
    --kes-key ${POOL_KES_PK} \
    --vrf-key ${POOL_VRF_PK} \
    --serial 1010101010 > stake_pool.cert

cat stake_pool.cert | $CLI certificate sign stake_key.sk > stake_pool.signcert

STAKE_POOL_ID=$(cat stake_pool.signcert | $CLI certificate get-stake-pool-id)
STAKE_POOL_CERT=$(cat stake_pool.signcert)

$CLI certificate new stake-delegation \
    ${STAKE_POOL_ID} \
    ${STAKE_KEY_PUB} > stake_delegation.cert
cat stake_delegation.cert | $CLI certificate sign stake_key.sk > stake_delegation.signcert
STAKE_DELEGATION_CERT=$(cat stake_delegation.signcert)


cat << EOF > genesis.yaml
blockchain_configuration:
  block0_date: 1550822014
  discrimination: test
  slots_per_epoch: 5000
  slot_duration: 10
  epoch_stability_depth: 10
  allow_account_creation: true
  consensus_genesis_praos_active_slot_coeff: 0.1
  consensus_leader_ids:
    - ${LEADER_PK}
  linear_fees:
    constant: 10
    coefficient: 0
    certificate: 0
  block0_consensus: genesis
  bft_slots_ratio: 0
  kes_update_speed: 43200 # 12hours
initial_certs:
  - ${STAKE_POOL_CERT}
  - ${STAKE_DELEGATION_CERT}
initial_funds:
  - address: ${FAUCET_ADDR}
    value: ${FAUCET_AMOUNT}
EOF

cat << EOF > poolsecret1.yaml
genesis:
  sig_key: ${POOL_KES_SK}
  vrf_key: ${POOL_VRF_SK}
  node_id: ${STAKE_POOL_ID}
EOF

cat << EOF > config.yaml
storage: "${PWD}/jormungandr-storage-test/"

rest:
  listen: "127.0.0.1:8443"
  prefix: "api"

peer_2_peer:
  trusted_peers: []
  public_address: "/ip4/127.0.0.1/tcp/8299"
  topics_of_interests:
    messages: low
    blocks: normal
EOF

$CLI genesis encode --input genesis.yaml --output block-0.bin

### PRINT

echo "faucet account: ${GREEN}${FAUCET_ADDR}${WHITE}"
echo "  * public: ${BLUE}${FAUCET_PK}${WHITE}"
echo "  * secret: ${RED}${FAUCET_SK}${WHITE}"
echo "  * amount: ${GREEN}${FAUCET_AMOUNT}${WHITE}"

echo "pool id: ${GREEN}${STAKE_POOL_ID}${WHITE}"

echo "To start the node:"
echo "$NODE --genesis-block block-0.bin --config config.yaml --secret poolsecret1.yaml"
