export const LOADING_DASHBOARD_DATA = 'LOADING_DASHBOARD_DATA'
export const DASHBOARD_DATA_LOADED = 'DASHBOARD_DATA_LOADED'
export const DASHBOARD_DATA_LOADING_FAILURE = 'DASHBOARD_DATA_LOADING_FAILURE'